Task1 changed
mustafakamber/mobillium-intern2024-task-solution pull request #3
Opened 2024-03-01 12:09 UTC by mustafakamber

2024-03-04 09:58 UTC, nezih94 commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +    <!-- MarginSize -->
İsimlendirme konusunda bence doğru yoldayız. Margin dimen değerlerini isimlendirirken, kullanım alanını belirten daha specific context verebiliriz. 

Ör: "normalMarginSize" yerine "regularHorizontalSpacing", "regularVerticalSpacing"

2024-03-04 15:27 UTC, iamkurtgoz commented on task-1-solution/FirstTaskSolution/app/src/main/res/values-night/themes.xml
> +    <style name="Theme.FirstTaskSolution" parent="Theme.MaterialComponents.DayNight.NoActionBar">
Burada default attr değerleri kalmış gibi görünüyor uygulama gündüz modunda gece modu gibi görünüyor ve gece modunda renkler bozuluyor. Eğer gece gündüz modu kullanacaksan buradaki renkleri düzenlemen gerekir eğer kullanmayacaksan gündüz modundaki değerleri aynı şekilde buraya kopyala-yapıştır.

2024-03-04 15:41 UTC, akndmr requested changes
Eline sağlık Mustafa, genel olarak düzenli ama bazı kısımlarda düzeltilmesi gereken noktalar var.
Özellikle spacing'lere bakış açımızı değiştirmemiz gerekiyor. Büyük spacing'ler olmadan `constraintlayout'`un nimetlerinden yararlanarak, layout'u tekrar düzenlemek gerekli.

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +    <dimen name="large900VerticalSpacing">124dp</dimen>
Eline sağlık düzenli olmuş ama layout içerisinde bu büyüklüklerde spacing kullanmak uygun değil. Küçük boyutlu ekranlarda bozulmalara sebebiyet verebilir.

En büyük spacing değeri `32dp` olabilir. İstinai durumlarda `48dp`'ye çıkabilir.

Aralarda ekstradan boşluk vermeden `constraint`'leri ayarlayabilmek `ConstraintLayout`'un bize sağladığı kolaylıklardan zaten. Bunu kullanmazsak, `ConstraintLayout`'dan tam faydalanmamış oluruz.

O yüzden bu task kapsamında `48dp` üzerindekileri kullanmayalım. Bundan sonraki task'larda da mümkün mertebe daha da düşük boşluklar kullanalım.

Konuştuğumuz sadece spacingler için. `width` ve `height` değerleri için bu kural daha fazla esnetilebilir.

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +
Gereksiz boşlukları kaldıralım. Tek boşluk olabilir.

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +
2 satır boşluk , 1'e düşebilir.

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/strings.xml
> +
Gereksiz boşluk

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/themes.xml
> +
Gereksiz boşluk

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/themes.xml
> +
Gereksiz boşluk

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/themes.xml
> +
Gereksiz boşluk

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +    <!-- VerticalSpacing -->
Bu yorum boşta kalmış. Kategorize etmek içinse, gerek yok çünkü altında ilgili kod bloğu yok. Kaldırabiliriz.

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/drawable/ic_launcher_background.xml
> +    android:width="108dp"
Hardcoded size

2024-03-04 15:41 UTC, akndmr commented on task-1-solution/FirstTaskSolution/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +    android:width="108dp"
Hardcoded size

2024-03-05 11:36 UTC, nezih94 commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +    <dimen name="wideTextSize">64sp</dimen>
"large'dan daha büyük" anlamına gelecek kelime bence "Wide" olmamalı. Daha uygun bir İngilizce kelime kullanabiliriz, örneğin "Huge"

2024-03-05 11:57 UTC, mustafakamber commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/dimens.xml
> +    <dimen name="wideTextSize">64sp</dimen>
Düzenledim hocam

2024-03-05 13:46 UTC, nezih94 approved these changes

2024-03-05 14:26 UTC, fatih-ozturk requested changes

2024-03-05 14:26 UTC, fatih-ozturk commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +        app:layout_constraintTop_toTopOf="@+id/temperatureText" />
referans verirken `@+id/` yerine `@id/` kullanalim.

https://medium.com/@nikhilschumifanikhil/android-basics-difference-between-id-and-id-f4eb66915361


```suggestion
        app:layout_constraintBottom_toBottomOf="@id/temperatureText"
        app:layout_constraintStart_toEndOf="@id/temperatureText"
        app:layout_constraintTop_toTopOf="@id/temperatureText" />
```

2024-03-05 14:26 UTC, fatih-ozturk commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +            android:layout_centerVertical="true"
bunlar relative layout'a ozel constraint layoutta islevsiz kaliyor. bu tarz problemleri duzeltelim.

2024-03-05 14:31 UTC, scotoglu requested changes

2024-03-05 14:31 UTC, scotoglu commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +            android:layout_marginBottom="17dp"
dimens.xml'den alabilir misin

2024-03-05 14:31 UTC, scotoglu commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +            android:layout_alignParentStart="true"
alignParentEnd, alignParentStart, centerVertical attributes relative layout ile birlikte kullanılıyor. Constraint layout içinde herhangi bir etkisi bulunmuyor. Bunları kaldırabilir misin. [Detay](https://halilozel1903.medium.com/android-relative-layout-kullanımı-394c75902d9d)

2024-03-05 18:14 UTC, scotoglu reviewed
Daha uzun textller geldiğinde TextView'lerin nasıl davrandığını görmek için `tools:text="@tools:sample/lorem[WordCount]"` kullanabilirsin.

2024-03-05 18:14 UTC, scotoglu commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +            android:id="@+id/nextSecondDayDateText"
tasarımda tarih gösterimi Çar, 03 Nisan formatında, peki bu tarihi Çarşamba, 03 Nisan 2024 şeklinde göstermek istesek nasıl olurdu? Metni değiştirdikten sonra, activity_weather.xml > design kısmında, sağ alt köşedeki ikon yardımıyla farklı ekranlar için kontrol edebilir misin?
![Screenshot 2024-03-05 at 20 31 51](https://github.com/mustafakamber/mobillium-intern2024-task-solution/assets/38690766/8689e957-4c6a-4894-82b0-e15ade36ca79)

2024-03-05 18:14 UTC, scotoglu commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +        android:text="@string/cityNameText"
İstanbul yerine, [buranın](https://tr.wikipedia.org/wiki/Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu#:~:text=Diğer%20ismi%20olan%20%22Taumatawhakatangihangakoauauotamateaurehaeaturipukakapikimaungahoronukupokaiwhenuakitanatahu%22%2092,ise%20105%20harften%20oluşmaktadır%2C%20bu) hava durumunu gösterdiğimizde,tasarımda bazı bozulmalar oluyor. Yine İstanbul metni kalsın ama diğer yerde gelicekmiş gibi genişlik ve kenar boşluklarını düzenleyebilir misin. Start ve End 16dp verilebilir yine.

2024-03-05 19:04 UTC, akndmr approved these changes
Sefa'nın da yorumları var sanırım. Onun dışında tamamdır. Eline sağlık 👏

2024-03-06 12:16 UTC, nezih94 commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +            android:id="@+id/nextSecondDayDateText"
@scotoglu Sefa ben bunu bilmiyordum :D

2024-03-06 12:24 UTC, nezih94 commented on task-1-solution/FirstTaskSolution/app/src/main/res/layout/activity_weather.xml
> +    android:background="?attr/colorSecondary"
Root layout background rengi için colorSecondary attribute kullanımı Material renk kurallarına göre çoğunlukla uygun değil. Mesela bunun yerine surface renk attribute'u kullanılabilir.

Material 2 ve Material 3 color system dökümantasyonlarına göz atabilirsin.
https://m2.material.io/design/color/the-color-system.html

2024-03-07 07:53 UTC, iamkurtgoz commented on task-1-solution/FirstTaskSolution/app/src/main/res/values/themes.xml
>      <style name="smallRegularText">
bir satır boşluk bırakalım

2024-03-07 07:53 UTC, iamkurtgoz commented on task-1-solution/FirstTaskSolution/app/src/main/res/values-night/themes.xml
>      <style name="smallRegularText">
bir satır boşluk bırakalım

2024-03-07 08:07 UTC, iamkurtgoz reviewed
themes içerisinde boşlukları düzenler misin

2024-03-07 12:44 UTC, iamkurtgoz approved these changes

2024-03-11 06:18 UTC, aliosmanay approved these changes

2024-03-11 06:44 UTC, basakyardim approved these changes

2024-03-11 06:50 UTC, scotoglu approved these changes

2024-03-11 10:41 UTC, fatih-ozturk approved these changes

2024-03-12 09:30 UTC, merged