TASK 2 :: OPERATIONS
mustafakamber/mobillium-intern2024-task-solution pull request #6
Opened 2024-03-14 14:39 UTC by mustafakamber

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/Constant.kt
> +object Constant{
object Constant sonrasına bir boşluk bırakabilir misin

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode1/DetailActivity.kt
> +        intent.apply {
intent içerisi okumayı farklı bir fonksiyona taşıyabiliriz

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode1/ListActivity.kt
> +        val callback = object : OnBackPressedCallback(true) {
callback işlemini fonksiyona bölelim

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode1/ListActivity.kt
> +        binding.listActivityRecyclerView.layoutManager = LinearLayoutManager(this)
liste ile alakalı işlemleri farklı bir fonksiyona taşıyalım

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode2/DetailFragment.kt
> +        val binding = FragmentDetailBinding.bind(view)
on create view içerisine taşıyalım

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode2/DetailFragment.kt
> +        val callback = object : OnBackPressedCallback(true) {
farklı fonksiyona taşıyalım

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode2/DetailFragment.kt
> +        bundle?.run {
farklı fonksiyona taşıyalım

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode2/FragmentToFragmentActivity.kt
> +        val callback = object : OnBackPressedCallback(true) {
farklı fonksiyona taşıyalım

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/Extension.kt
> +    fun Fragment.getFragment(appCompatActivity: AppCompatActivity, bundle: Bundle? = null) {
ismi route, navigate prefix olabilir

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/Extension.kt
> +    fun Activity.getActivity(destinationActivity: Activity,city : City? = null){
startActivity olabilir, 

fun Activity.startActivity(destinationActivity: Activity, city: City? = null){

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode2/FragmentToFragmentActivity.kt
> +        ListFragment().getFragment(this)
ListFragment.newInstance() olacak şekilde düzenleyelim

2024-03-18 14:23 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/main/MainActivity.kt
> +
boşlukları silelim

2024-03-18 15:21 UTC, akndmr reviewed
Eline sağlık, Mustafa.
Sadece bir kaç dosyaya bakabildim. Kalanına müsait olunca bakarım.
Daha düzenli ve güzel görünüyor.
Bir kaç  ufak yorumum oldu.

2024-03-18 15:21 UTC, akndmr commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/Extension.kt
> +    fun Activity.getActivity(destinationActivity: Activity,city : City? = null){
İçeriğine bakınca yaptığı işi ifade etmeyen bir fonksiyon ismi. O yüzden `navigateToActivityWithExtras(...)` veya `startActivityWithExtras(...)` gibi daha ifade edici isimlendirme yapılabilir.

Ayrıca, tüm sayfalarda `command + option + L`(Mac) yaparak bazı basit formatlama ya da linting hatalarını giderebiliriz: 
Örnek: `destinationActivity: Activity,city : City ` burada virgülden sonra bir boşluk gelmeli. Aşağıda farklı bir yerde de böyle bir formatting hatası var.

2024-03-18 15:21 UTC, akndmr commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode2/ListFragment.kt
> +        binding.listFragmentRecyclerView.layoutManager = LinearLayoutManager(context)
LayoutManager ile ilgili yapacağımız ekstra bir şey yok ise, direkt XML'den verebiliriz.
`layoutManager=""`

2024-03-18 15:21 UTC, akndmr commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/model/City.kt
> +    val cityTemperatureMax : Int
Kotlin trailing comma konusuna bakabilirsin. Şu an şart değil.

2024-03-18 18:04 UTC, scotoglu requested changes

2024-03-18 18:04 UTC, scotoglu commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/model/City.kt
> +    val cityId: Int,
city prefixleri kaldırabilir.

2024-03-18 18:04 UTC, scotoglu commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/CityDataSource.kt
> +                1, "İstanbul",
değerleri verirken hangi alana karşılık kullanıldığını da yazarsak daha okunulabilir olur.` id = 1, name = "İstanbul"`

2024-03-18 18:04 UTC, scotoglu commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/Extension.kt
> +    fun Fragment.getFragment(appCompatActivity: AppCompatActivity, bundle: Bundle? = null) {
FragmentExt olarak ayrı bir extension dosyası oluşturabiliriz.

2024-03-18 18:04 UTC, scotoglu commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/Extension.kt
> +    fun Activity.getActivity(destinationActivity: Activity,city : City? = null){
ActivityExt olarak ayrı bir extension dosyası oluşturabiliriz.

2024-03-18 18:04 UTC, scotoglu commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/view/episode3/ListNavFragment.kt
> +        val callback = object : OnBackPressedCallback(true) {
Back aksiyonu için extension fonksiyonu yazabilir miyiz? `onBackPressed`, `handleBackPressed` olarak isimlendirilebilir. ActivityExt içerisine ekleyebilirsin. 

```
// Usage
onBackPressed {
  requireActivity().finish()
}
```

2024-03-20 14:08 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/util/ActivityController.kt
> +                    putExtra(CITY_DATA,city)
boşluk bırakalım

2024-03-20 14:08 UTC, iamkurtgoz commented on task-2-solution/SecondTaskSolution/app/src/main/java/com/example/secondtasksolution/adapter/CityAdapter.kt
> +                "$temperatureMin° - $temperatureMax°"
gereksiz boşluğu silelim

2024-03-21 14:08 UTC, fatih-ozturk approved these changes

2024-03-21 14:08 UTC, basakyardim approved these changes

2024-03-21 14:09 UTC, scotoglu approved these changes
Eline sağlık

2024-03-22 10:27 UTC, aliosmanay approved these changes

2024-03-25 14:22 UTC, merged